language: rust

rust:
  - stable
  - nightly
  - beta

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

notifications:
  email: false

jobs:
  include:
    - name: fmt-check
      if: type = pull_request
      script:
        - cargo fmt --all -- --check
