language: rust

rust:
  - stable
  - nightly
  - beta

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

notifications:
  email: false

before_install:
  - deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main
  - deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main
  - sudo apt update
  - sudo apt install -y llvm-10-dev

jobs:
  include:
    - name: fmt-check
      if: type = pull_request
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
