[package]
name = "error"
authors = ["Jeremy Schwartz <j.schwartz564@icloud.com>"]
version = "0.0.1-alpha"
edition = "2018"

[lib]
name = "error"

[dependencies]
colored = "1.9.3"
itertools = "0.9.0"

[dev-dependencies]
